export const itaLangPack = {
  common: { title: "Flavia Scirè" },
  mainPage: {
    worksButton: "works",
    aboutButton: "about",
  },
  aboutPage: {
    content: `Flavia Scirè è una visual designer e curatrice, classe 1994, vive e lavora a Milano. Nel 2017 si è laureata in pittura e arti visive alla NABA, nuova accademia di belle arti, e nel 2019 ha conseguito la laurea specialistica in arti visive e studi curatoriali.La sua ricerca visuale si basa su percezione, simboli e immaginari collettivi nei contesti della comunicazione contemporanea. Da sempre affascinata dalla magia della carta stampata, incontra l'universo parallelo del digitale nel corso dei suoi studi in antropologia dei media.`,
    downloadCvButton: "download cv",
    switchLangButton: "switch language",
    portrait: "/foto_flo.png",
  },
  contents: [
    {
      preview: "immagini/WALLPEPPER/24jpg/Aura_amb2.png",
      images: [
        
     "immagini/WALLPEPPER/24jpg/Beat_WP-138-A.jpg",
     "immagini/WALLPEPPER/24jpg/Beat_WP-138-B.jpg",      
     "immagini/WALLPEPPER/24jpg/Beat_WP-138-A_ZOOM.jpg",               
     "immagini/WALLPEPPER/24jpg/Beat_AMB2.jpg",

     "immagini/WALLPEPPER/24jpg/Magrathea_WP-139-A.jpg",
     "immagini/WALLPEPPER/24jpg/Magrathea_WP-139-B.jpg",      
     "immagini/WALLPEPPER/24jpg/Magrathea_WP-139-C.jpg",               
     "immagini/WALLPEPPER/24jpg/Magrathea_WP-139-A_ZOOM.jpg",
     "immagini/WALLPEPPER/24jpg/Magrathea_amb.jpg",

     "immagini/WALLPEPPER/24jpg/Holo-Marble_WP-135-B.jpg",
     "immagini/WALLPEPPER/24jpg/Holo-Marble_WP-135-A.jpg",      
     "immagini/WALLPEPPER/24jpg/Holo-Marble_WP-135-C.jpg",               
     "immagini/WALLPEPPER/24jpg/Holo-Marble_WP-135-A_ZOOM.jpg",
     "immagini/WALLPEPPER/24jpg/Holomarble_amb.jpg",

     "immagini/WALLPEPPER/24jpg/Passiflora_WP-137-B.jpg",
     "immagini/WALLPEPPER/24jpg/Passiflora_WP-137-A.jpg",      
     "immagini/WALLPEPPER/24jpg/Passiflora_WP-137-C.jpg",               
     "immagini/WALLPEPPER/24jpg/Passiflora_WP-137-A_ZOOM.jpg",
     "immagini/WALLPEPPER/24jpg/Passiflora_ambB.jpg",

     "immagini/WALLPEPPER/24jpg/Aura_WP-136-A.jpg",
     "immagini/WALLPEPPER/24jpg/Aura_WP-136-B.jpg",  
     "immagini/WALLPEPPER/24jpg/Aura_WP-136-C.jpg",     
     "immagini/WALLPEPPER/24jpg/Aura_WP-136-D.jpg",                
     "immagini/WALLPEPPER/24jpg/Aura_WP-136-A_ZOOM.jpg",
     "immagini/WALLPEPPER/24jpg/Aura_amb.jpg",
     "immagini/WALLPEPPER/24jpg/Aura_amb2.jpg",
    

      ],
      title: "Wallpepper 2024",
      description:
        "Contributi al catalogo 2024 di Wallpepper/Group. Questa serie di wallpaper design nasce dall’esplorazione dell’incontro tra texture naturali e digitali, un’ibridazione che cerca di fondere il calore organico con l’estetica contemporanea. Le forme geometriche semplici sono ispirate all’astrattismo geometrico della pittura della seconda metà del XX secolo, reinterpretate qui per dialogare con la versatilità del mondo digitale. Il risultato è una serie di superfici dinamiche che arricchiscono l’ambiente con un senso di profondità e una spiccata modernità. ",
    },
    {
      preview: "/immagini/WALLPEPPER/23_jpg/TG_C_ZOOM.jpg",
      images: [
        "/immagini/WALLPEPPER/23_jpg/Ceramic_flow.jpg",
        "/immagini/WALLPEPPER/23_jpg/ceramic_flow-zoom1.jpg",
        "/immagini/WALLPEPPER/23_jpg/Ceramic_Flow-AMB.jpg",

        "/immagini/WALLPEPPER/23_jpg/TG_A.jpg",
        "/immagini/WALLPEPPER/23_jpg/TG_A_ZOOM.jpg",
        "/immagini/WALLPEPPER/23_jpg/TG_B_ZOOM.jpg",
        "/immagini/WALLPEPPER/23_jpg/TG_C_ZOOM.jpg",
        "/immagini/WALLPEPPER/23_jpg/TG_D_ZOOM.jpg",
        "/immagini/WALLPEPPER/23_jpg/TG-E-ZOOM.jpg",
        "/immagini/WALLPEPPER/23_jpg/TG_AMB.jpg",

        "/immagini/WALLPEPPER/23_jpg/stream_dream_A.jpg",
        "/immagini/WALLPEPPER/23_jpg/stream_dream_B.jpg",
        "/immagini/WALLPEPPER/23_jpg/stream_dream_A_zoom.jpg",
        "/immagini/WALLPEPPER/23_jpg/stream_dream_B_zoom.jpg",
        "/immagini/WALLPEPPER/23_jpg/stream_dream_amb.jpg",
      
        "/immagini/WALLPEPPER/23_jpg/galaxy.jpg",
        "/immagini/WALLPEPPER/23_jpg/galaxy_zoom.jpg",
        "/immagini/WALLPEPPER/23_jpg/galaxy_amb.jpg",

        "/immagini/WALLPEPPER/23_jpg/space_venture.jpg",
        "/immagini/WALLPEPPER/23_jpg/space_venture_zoom.jpg",
        "/immagini/WALLPEPPER/23_jpg/space_venture_amb.jpg",

        "/immagini/WALLPEPPER/23_jpg/RSG.jpg",
        "/immagini/WALLPEPPER/23_jpg/RSG_zoom.jpg",
        "/immagini/WALLPEPPER/23_jpg/RSG_amb.jpg",

      ],
      title: "Wallpepper 2023",
      description:
        "Wallpaper design realizzati per il catalogo 2023 di Wallpepper/Group. Questa collezione combina mondi visivi diversi attraverso una reinterpretazione allo stesso tempo astratta e materica di immagini fotografiche e dell'estetica digitale vintage. Le texture sono nate dalla decostruzione e rielaborazione di fotografie, trasformate digitalmente per creare composizioni inedite e astratte, che portano nuove profondità agli spazi. La sezione dedicata ai bambini e ragazzi si ispira al fascino nostalgico dei videogiochi anni ’80 e ’90, reinterpretando i pixel con un approccio materico che richiama i mattoncini da costruzione.",
    },
    {
      preview: "/immagini/BORDERLINED/galleryI/Vol.1_Pagina_05.jpg",
      images: [
        "/immagini/BORDERLINED/galleryI/Vol.1_Pagina_01.jpg",
        "/immagini/BORDERLINED/galleryI/Vol.1_Pagina_02.jpg",
        "/immagini/BORDERLINED/galleryI/Vol.1_Pagina_04.jpg",
        "/immagini/BORDERLINED/galleryI/Vol.1_Pagina_05.jpg",
        "/immagini/BORDERLINED/galleryI/Vol.1_Pagina_14.jpg",
        "/immagini/BORDERLINED/galleryI/Vol.1_Pagina_16.jpg",
        "/immagini/BORDERLINED/galleryI/Vol.1_Pagina_25.jpg",
        "/immagini/BORDERLINED/galleryI/Vol.1_Pagina_27.jpg",
        "/immagini/BORDERLINED/galleryI/Vol.1_Pagina_33.jpg",
        "/immagini/BORDERLINED/galleryI/Vol.1_Pagina_34.jpg",
        "/immagini/BORDERLINED/galleryI/Vol.1_Pagina_36.jpg",
        "/immagini/BORDERLINED/galleryI/Vol.1_Pagina_41.jpg",

        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_01.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_02.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_06.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_07.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_09.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_10.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_12.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_13.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_22.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_23.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_26.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_27.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_33.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_36.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_37.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_43.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_54.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_55.jpg",
        "/immagini/BORDERLINED/galleryII/Vol.2_Pagina_61.jpg",

        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_01.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_03.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_04.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_09.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_12.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_13.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_14.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_17.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_21.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_22.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_25.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_28.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_29.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_33.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_35.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_38.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_40.jpg",
        "/immagini/BORDERLINED/galleryIII/Postreality_Pagina_42.jpg",
      ],
      title: "Borderlined",
      description:
        "Borderlined è un progetto editoriale iniziato come ricerca antropologico-visuale sui temi della formazione identitaria ed emotiva negli individui nativi digitali. L'intenzione di rendere la mia ricerca più accessibile e appetibile mi ha spinto a scegliere la forma del magazine, dove i concetti teorici si relazionano a stretto giro con le immagini che li esemplificano, creando un prodotto coinvolgente ed efficace. Il progetto si articola in tre volumi: The Perfect Shot (2016), E-motions (2017) e Postreality (2019). Ogni volume esplora il rapporto tra la percezione della realtà e le immagini in rete attraverso uno studio antropologico-visivo, affrontando temi diversi legati all'uso delle immagini digitali e al loro impatto sulla costruzione della realtà contemporanea. Attraverso una combinazione di saggi, analisi visive e contributi interdisciplinari, Borderlined invita i lettori a riflettere criticamente su come le immagini online modellano la nostra comprensione del mondo e delle identità culturali.",
        
    },
    
    {
      preview: "/immagini/PORTS/07.gif",
      images: [
        "/immagini/PORTS/01.gif",
        "/immagini/PORTS/02.gif",
        "/immagini/PORTS/03.gif",
        "/immagini/PORTS/04.gif",
        "/immagini/PORTS/05.gif",
        "/immagini/PORTS/06.gif",
        "/immagini/PORTS/07.gif",
        "/immagini/PORTS/08.gif",
        "/immagini/PORTS/09.gif",
        "/immagini/PORTS/10.gif",
      ],
      title: "Ports",
      description:
        "GIF animate per la promozione social della collezione spring/summer 2021, realizzate a partire dalle illustrazioni originali stampate sui capi",
    },
    { 
      preview: "/immagini/ELEKTROPARK/fish/fish_and_djs_IG_post2.jpg",
      images: [
        "/immagini/ELEKTROPARK/fish/story_2.mp4",
        "/immagini/ELEKTROPARK/fish/story_3.mp4",
        "/immagini/ELEKTROPARK/fish/story_4.mp4",
        "/immagini/ELEKTROPARK/fish/story_5.mp4",
        "/immagini/ELEKTROPARK/fish/story.mp4",
        "/immagini/ELEKTROPARK/spiaggia_immaginaria/story_spiaggia_immaginaria.mp4",
        "/immagini/ELEKTROPARK/sleeping_concert/sleepin_sory.mp4",
        "/immagini/ELEKTROPARK/blackmed/blackmed_story.mp4",
      ],
      title: "Electropark",
      description:
        "Nel 2020 ho collaborato come grafica e art director con Elektropark, il festival musicale genovese dedicato alla musica elettronica e alle arti digitali. Per l'edizione di quell'anno, ho curato la realizzazione di tutti i materiali di comunicazione, sia social che cartacei, degli eventi del festival. Il mio lavoro si è concentrato sulla creazione di una linea visiva coerente e d'impatto, capace di riflettere l'identità innovativa e sperimentale del festival, con l'obiettivo di coinvolgere il pubblico e valorizzare la programmazione artistica attraverso un design dinamico e riconoscibile.",
    },

  
    {
      preview: "/immagini/FIELDWORK/africaloro/View-01.jpg",
      images: [
        "/immagini/FIELDWORK/africaloro/View-01.jpg",
        "/immagini/FIELDWORK/africaloro/View-05.jpg",
        "/immagini/FIELDWORK/africaloro/View-062.jpg",
        "/immagini/FIELDWORK/museococaina/View-04.jpg",
        "/immagini/FIELDWORK/museococaina/View-06.jpg",
        "/immagini/FIELDWORK/museococaina/View-052.jpg",
      ],
      title: "Milieu edizioni",
      description:
        "Per la collana Fieldwork della casa editrice Milieu, specializzata in testi antropologici, ho progettato le copertine di due libri, adottando un design estremamente semplice e pulito. L'obiettivo era quello di dare massimo risalto all'immagine scelta per lo sfondo di ogni volume, solitamente una texture o un tessuto che rappresenta visivamente l'argomento trattato nel libro. Questo approccio minimalista permette al lettore di entrare immediatamente in contatto con l'essenza del contenuto, creando una connessione visiva e sensoriale con il tema esplorato dall'autore.",
    },
    {
      preview: "/immagini/ARTOPIA/inviti/gallery/1.jpg",
      images: [
        "/immagini/ARTOPIA/inviti/gallery/1.jpg",
        "/immagini/ARTOPIA/inviti/gallery/2.jpg",
        "/immagini/ARTOPIA/inviti/gallery/3.jpg",
        "/immagini/ARTOPIA/inviti/gallery/4.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0138.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0141.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0145.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0147.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0150.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0152.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0154.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0158.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0160.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0140.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0142.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0146.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0149.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0151.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0153.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0155.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0159.jpg",
        "/immagini/ARTOPIA/cataloghi/DSC_0161.jpg",
      
      ],
      title: "Artopia Gallery",
      description:
        "Come assistente di galleria presso la storica galleria Artopia di Milano, ho contribuito all'organizzazione di mostre, fiere ed eventi, collaborando con artisti, curatori e collezionisti per garantire la realizzazione di progetti espositivi di successo. Mi sono occupata della cura del design e della pubblicazione di inviti e cataloghi, sviluppando contenuti visivi e materiali promozionali che riflettessero l'identità della galleria e degli artisti rappresentati, e supportando la galleria nella sua comunicazione e promozione nel contesto artistico contemporaneo.",
    },
  ],
};
